project:
  type: website
  output-dir: docs

website:
  title: "Rajan AI Website"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rajandevkota98
      - icon: linkedin
        href: https://www.linkedin.com/in/rajan-devkota-927340175/
format:
  html:
    theme: cosmo
    css: styles.css

paths:
  python: /home/user/Downloads/blogs/myenv/bin/python3



